version: '3'
services:
  node:
    build:
       context: .
       dockerfile: Dockerfile
    container_name: node-container
    volumes:
      - ./src:/home
    ports:
       - 3000:3000
    command: sh -c 'yarn install & yarn dev'
    links:
      - "redis"
  redis:
    image: redis:latest
    restart: always
    container_name: redis-container
    volumes:
        - ./store/redis:/data
    ports:
        - "6379:6379"
    command: redis-server --appendonly yes
